<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net481;net8.0-windows;net9.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Agilent.Testables.Process.Tests</AssemblyName>
    <RootNamespace>Agilent.Testables.Process.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <PlatformName>windows</PlatformName>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net9.0-windows'">
    <DefineConstants>NET9_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0-windows'">
    <DefineConstants>NET8_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net481'">
    <DefineConstants>NET481</DefineConstants>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net48'">
    <DefineConstants>NET48</DefineConstants>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <_SkipUpgradeNetAnalyzersNuGetWarning>true</_SkipUpgradeNetAnalyzersNuGetWarning>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.0" />
    <PackageReference Include="Snapshooter.MSTest" Version="0.14.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Process\Process.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows' Or '$(TargetFramework)' == 'net9.0-windows'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="__snapshots__\" />
  </ItemGroup>

</Project>
