<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputType>Library</OutputType>
    <RootNamespace>Agilent.Testables.Process</RootNamespace>
    <AssemblyName>Agilent.Testables.Process</AssemblyName>
    <Authors>Agilent</Authors>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\..\..\release-notes.txt"))</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>
      This package contains an abstraction of the static System.Process class found in .NET Framework 4.8 and .NET 8.0. It allows for an IProcess interface to be used instead for easier testing.
    </Description>
    <PackageProjectUrl>https://github.com/Agilent/Agilent.Testables.AppDomain</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Agilent/Agilent.Testables.AppDomain</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>process, iprocess, iprocessfactory, processfactory, testing, ioc, dependency injection, agilent</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath=""/>
    <None Include="..\..\images\icon.png" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net48;net481;net8.0-windows;net9.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net9.0-windows'">
    <DefineConstants>NET9_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0-windows'">
    <DefineConstants>NET8_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net481'">
    <DefineConstants>NET481</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net48'">
    <DefineConstants>NET48</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" PrivateAssets="All">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Security.SecureString" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>**/Wrappers/**</Value>
    </SonarQubeSetting>
  </ItemGroup>


</Project>
